title: Conquer medieval
tagline: Conquer versão 5095

author:
  name: Conquer medieval
  email: nilsonlinux@gmail.com
  twitter: nilsonlinux
  github: nilsonlinux
  
include: ['_pages']
  
layout: post
permalink: /:categories/:title/

url: http://conquermedieval.github.io

markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
